@startuml Alarm State Diagram
state "Alarm Task" as AlarmTask {
    [*] --> Idle
    Idle --> SetAlarm : bSetAlarm = TRUE
    SetAlarm --> AlarmON : AlarmTimer.Q = TRUE
    AlarmON --> Idle : bReset = TRUE
}

@enduml
