@startuml Alarm State Diagram (MAIN)
state "MAIN Task" as AlarmTask {
    [*] --> Idle
    Idle --> SetAlarm : bSetAlarm = TRUE
    SetAlarm --> AlarmON : AlarmTimer.Q = TRUE
    AlarmON --> Idle : bReset = TRUE
}

@enduml
