@startuml Coffee_State_Diagram
State "Cofee Task" as CoffeeTask {
[*] --> Idle 
Idle--> Brewing : bAlarmON = TRUE AND bLightsON = TRUE AND bWorkdayStatus = TRUE
Brewing --> CoffeeReady : CoffeeTimer.Q = TRUE
CoffeeReady --> Idle : bReset = TRUE
}

@enduml