@startuml Lights State Diagram
state "Lights Task" as LightsTask {
    [*] --> Off
    Off --> Delay : bAlarmON = TRUE
    Delay --> LightsON : LightDelayTimer.Q = TRUE
    LightsON --> Off : bReset = TRUE
}

@enduml
