@startuml
state "Morning Routine" as Routine {
    [*] --> Idle

    Idle --> SetAlarm : bSetAlarm = TRUE
    SetAlarm --> AlarmON : AlarmTimer.Q = TRUE
    AlarmON --> LightDelay : bAlarmON = TRUE
    LightDelay --> LightsON : LightDelayTimer.Q = TRUE
    LightsON --> CheckWorkDay : bLightsON = TRUE
    CheckWorkDay --> IsWorkDay : bWorkDayStatus = TRUE
    CheckWorkDay --> NotWorkDay : bWorkDayStatus = FALSE

    IsWorkDay --> Brewing : bLightsON = TRUE AND bAlarmON = TRUE
    NotWorkDay --> Resetting : bReset = TRUE

    Brewing --> CoffeeReady : CoffeeTimer.Q = TRUE
    CoffeeReady --> Resetting : bReset = TRUE

    Resetting --> Idle : ResetTimer.Q = TRUE
}

@enduml
