@startuml Sequence Diagram Communcation Morning Routine
actor User

participant MainTask
participant LightTask
participant WorkdayTask
participant CoffeeTask
participant ResetTask

User -> MainTask : Start Routine

MainTask -> LightTask : Trigger Lights
LightTask -> MainTask : Acknowledge Lights Turned On

MainTask -> WorkdayTask : Check if Workday

WorkdayTask -> MainTask : Return Workday Status and Current Day

MainTask -> CoffeeTask : Start Brewing Coffee (if workday)
CoffeeTask -> MainTask : Coffee Ready

MainTask -> ResetTask : Trigger Reset
ResetTask -> MainTask : Acknowledge Reset Complete

@enduml
